config/routes.rb
Rails.application.routes.draw do
  resources :board_messages
  resources :board_users
  resources :data_pages
  devise_for :accounts
  get 'ajax/index'

  resources :questionary_results
  resources :questionary_choices
  resources :questionary_items
  resources :questionaries
  resources :answers
  resources :questions
  resources :mycontacts
  get 'blogs/index'

  get 'blogs/genre'

  get 'blogs/show'

  get 'blogposts/index'

  get 'blogposts/add'

  get 'blogposts/edit'

  get 'blogposts/delete'

  get 'bloggenres/index'

  get 'bloggenres/add'

  get 'bloggenres/edit'

  get 'blogconfigs/index'

  get 'blogconfigs/edit'

  get 'messages/index'

  get 'messages/how'

  get 'messages/add'

  get 'messages/edit'

  get 'people/index'
  get 'people', to: 'people#index'

  get 'people/add'
  post 'people/add', to: 'people#create'

  get 'people/edit/:id', to: 'people#edit'
  post 'people/edit/:id', to: 'people#update'
  patch 'people/edit/:id', to: 'people#update'

  get 'people/delete/:id', to: 'people#delete'

  get 'people/find'
  post 'people/find'

  get 'people/:id', to: 'people#show'

  get 'messages/index'
  get 'messages', to: 'messages#index'

  get 'messages/add'
  post 'messages/add', to: 'messages#create'

  get 'messages/edit/:id', to: 'messages#edit'
  patch 'messages/edit/:id', to: 'messages#update'

  get 'messages/delete/:id', to: 'messages#delete'

  get 'messages/:id', to: 'messages#show'

  get 'cards/index'
  get 'cards', to: 'cards#index'

  get 'cards/show'

  get 'cards/add'
  post 'cards/add'

  get 'cards/:id', to: 'cards#show'

  get 'cards/edit/:id', to: 'cards#edit'
  patch 'cards/edit/:id', to: 'cards#edit'

  get 'cards/delete/:id', to: 'cards#delete'

  get 'dengonban/index'

  get 'helo/index'
  get 'helo', to: 'helo#index'
  get 'helo/other'
  post 'helo', to: 'helo#index'
  post 'helo/index'

  get 'ajax/data'
  post 'ajax/data'
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :quqestion
  validates :content, :name, presence: {message:'は、必須項目です。'}
end

app/models/blogconfig.rb
class Blogconfig < ApplicationRecord
  validates :title, :stylename, presence: {message:'は、必須項目です。'}
end

app/models/bloggenre.rb
class Bloggenre < ApplicationRecord
  has_many :blogpost

  validate name, presence: {message: 'は、必須項目です。'}
end

app/models/blogpost.rb
class Blogpost < ApplicationRecord
  belongs_to :bloggenre

  validates :title, :content, presence: {message:'は、必須項目です。'}
end

app/models/board_message.rb
class BoardMessage < ApplicationRecord
  belongs_to :board_user

  validates :content, presence: {message:'は、必須項目です。'}
end

app/models/board_user.rb
class BoardUser < ApplicationRecord
  belongs_to :account
  has_many :board_message

  validates :nickname, presence: {message:'は、必須項目です。'}
end

app/models/card.rb
class Card < ApplicationRecord
end

app/models/data_page.rb
class DataPage < ApplicationRecord
end

app/models/email_validator.rb
class EmailValidator < ActiveModel::EachValidator

  def validate_each(record, attribute, value)
    unless value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
      record.errors[attribute] << (options[:message] || "is not an email")
    end
  end

end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :person

  validates :message, presence: {message:'を書いてください。'}
end

app/models/mycontact.rb
class Mycontact < ApplicationRecord
  validates :name, presence: {message:'は、必須項目です。'}
  validates :age, numericality: {message:'は、数字で入力ください。'}
  validates :nationality, inclusion: {in: [true, false], message:'は、真偽値です。'}
end

app/models/person.rb
class Person < ApplicationRecord
  has_many :message

  validates :name, presence: {message:'は、必須項目です。'}
  validates :age, numericality: {message:'は、数字で入力ください。'}
  validates :mail, email: {message:'はメールアドレスではありません。'}
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answer
  validates :content, :name, presence: {message:'は、必須項目です。'}
end

app/models/questionary.rb
class Questionary < ApplicationRecord
  has_many :questionary_item
  has_many :questionary_result

  validates :title, :description, :deadline, presence: {message:'は、必須項目です。'}
end

app/controllers/board_users_controller.rb
class BoardUsersController < ApplicationController
  before_action :set_board_user, only: [:show, :edit, :update, :destroy]

  # GET /board_users
  # GET /board_users.json
  def index
    @board_users = BoardUser.all
  end

  # GET /board_users/1
  # GET /board_users/1.json
  def show
  end

  # GET /board_users/new
  def new
    @board_user = BoardUser.new
  end

  # GET /board_users/1/edit
  def edit
  end

  # POST /board_users
  # POST /board_users.json
  def create
    @board_user = BoardUser.new(board_user_params)

    respond_to do |format|
      if @board_user.save
        format.html { redirect_to @board_user, notice: 'Board user was successfully created.' }
        format.json { render :show, status: :created, location: @board_user }
      else
        format.html { render :new }
        format.json { render json: @board_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /board_users/1
  # PATCH/PUT /board_users/1.json
  def update
    respond_to do |format|
      if @board_user.update(board_user_params)
        format.html { redirect_to @board_user, notice: 'Board user was successfully updated.' }
        format.json { render :show, status: :ok, location: @board_user }
      else
        format.html { render :edit }
        format.json { render json: @board_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /board_users/1
  # DELETE /board_users/1.json
  def destroy
    @board_user.destroy
    respond_to do |format|
      format.html { redirect_to board_users_url, notice: 'Board user was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_board_user
      @board_user = BoardUser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def board_user_params
      params.require(:board_user).permit(:nickname, :account_id, :memo)
    end
end

app/helpers/ajax_helper.rb
module AjaxHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/board_users_helper.rb
module BoardUsersHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/helo_helper.rb
module HeloHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/board_users/_form.html.erb
<%= form_with(model: board_user, local: true) do |form| %>
  <% if board_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(board_user.errors.count, "error") %> prohibited this board_user from being saved:</h2>

      <ul>
      <% board_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nickname %>
    <%= form.text_area :nickname, id: :board_user_nickname %>
  </div>

  <div class="field">
    <%= form.label :account_id %>
    <%= form.number_field :account_id, id: :board_user_account_id %>
  </div>

  <div class="field">
    <%= form.label :memo %>
    <%= form.text_area :memo, id: :board_user_memo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/board_users/edit.html.erb
<h1>Editing Board User</h1>

<%= render 'form', board_user: @board_user %>

<%= link_to 'Show', @board_user %> |
<%= link_to 'Back', board_users_path %>

app/views/board_users/index.html.erb
<h1>User Home</h1>
<h2>※<%=@board_user.account.email %> さんの設定</h2>
<%= render 'form', board_user: @board_user %>
<hr>
<p><%=link_to '<< go back', controller: :board_messages %></p>

<hr>
<div>copyright SYODA-Tuyano 2016.</div>

app/views/board_users/new.html.erb
<h1>New Board User</h1>

<%= render 'form', board_user: @board_user %>

<%= link_to 'Back', board_users_path %>

app/views/board_users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nickname:</strong>
  <%= @board_user.nickname %>
</p>

<p>
  <strong>Account:</strong>
  <%= @board_user.account_id %>
</p>

<p>
  <strong>Memo:</strong>
  <%= @board_user.memo %>
</p>

<%= link_to 'Edit', edit_board_user_path(@board_user) %> |
<%= link_to 'Back', board_users_path %>